<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="4" failures="1" errors="0" time="2.156">
  <testsuite name="ErrorHandler" errors="0" failures="0" skipped="0" timestamp="2021-01-13T20:12:06" time="0.342" tests="1">
    <testcase classname="ErrorHandler should handle error" name="ErrorHandler should handle error" time="0.004">
    </testcase>
  </testsuite>
  <testsuite name="authentication.service" errors="0" failures="1" skipped="0" timestamp="2021-01-13T20:12:06" time="1.515" tests="3">
    <testcase classname="authentication.service login should return error if no user found" name="authentication.service login should return error if no user found" time="0.004">
    </testcase>
    <testcase classname="authentication.service login should return error if user password in invalid" name="authentication.service login should return error if user password in invalid" time="0.001">
    </testcase>
    <testcase classname="authentication.service login should return JWT is user logins properly" name="authentication.service login should return JWT is user logins properly" time="0.003">
      <failure>Error: expect(received).resolves.toEqual(expected) // deep equality

Expected: &quot;JW1T&quot;
Received: &quot;JWT&quot;
    at Object.toEqual (/Users/dmytro.zharkov/Projects/experiments/social-messages/node_modules/expect/build/index.js:202:20)
    at /Users/dmytro.zharkov/Projects/experiments/social-messages/src/modules/authentication/services/authentication.service.test.ts:75:79
    at Generator.next (&lt;anonymous&gt;)
    at /Users/dmytro.zharkov/Projects/experiments/social-messages/src/modules/authentication/services/authentication.service.test.ts:8:71
    at new Promise (&lt;anonymous&gt;)
    at Object.&lt;anonymous&gt;.__awaiter (/Users/dmytro.zharkov/Projects/experiments/social-messages/src/modules/authentication/services/authentication.service.test.ts:4:12)
    at Object.&lt;anonymous&gt; (/Users/dmytro.zharkov/Projects/experiments/social-messages/src/modules/authentication/services/authentication.service.test.ts:62:68)
    at Object.asyncJestTest (/Users/dmytro.zharkov/Projects/experiments/social-messages/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at /Users/dmytro.zharkov/Projects/experiments/social-messages/node_modules/jest-jasmine2/build/queueRunner.js:43:12
    at new Promise (&lt;anonymous&gt;)</failure>
    </testcase>
  </testsuite>
</testsuites>